### ISSUE TITLE
amazing work. 2 questions

### ISSUE THREAD

**Issue by hiqsociety** [gstrauss/mcdb#11]
1. anyone used in production so far? just curious if it's production ready etc
2. possible to provide golang binding for this?

i can sponsor a few coffees for 2. if this is production ready

**Comment by gstrauss** [comment]
You questions in #11 and #12 do not demonstrate any credibility in your ability to assess the quality of the work.  Quite the opposite.

> anyone used in production so far?

Your ability to answer your own simple questions is severely lacking.
* this repo was pushed to github some 12 years ago
* this repo has 103 stars on github (seems like a few other people might be using it)
* this repo has a few other issues that have been closed, which it does not seem you have taken any time to review.
* yes it is used in production

> possible to provide golang binding for this?

Possible?  Yes.  Likely?  Not for you.

You posted two issues: #11 and #12 on a project that has been on github for over 12 years.   Two issues out of 12 are now yours an a 12 year-old repo.  This is not a place for your simpleton questions.   You don't even realize how out-of-touch you are posting such questions to an issue tracker.  "amazing work.  2 questions" is  a *terrible* subject for an issue.  Maybe you meant to use the Discussions tab?  Since you can not be bothered to do the most basic evaluation of a project before asking simpleton questions, I do not think mcdb is right for you.  Please go away.

**Comment by hiqsociety** [comment]
@gstrauss ok. i just saw the discussion tab so moving it there.

p.s. : sorry i just found out about constant database here
https://en.wikipedia.org/wiki/Cdb_(software)

merry xmas by the way
